#!/usr/bin/env zsh

# _yavm_debug "Setting path for go."

local version entries_to_add=()
for version in ${(s: :)_yavm_versions[go]}; do
  if [[ -d "$ASDF_DIR/installs/golang/$version/go/bin" ]]; then
    entries_to_add+=("$ASDF_DIR/installs/golang/$version/go/bin")
  else
    _yavm_warn "go version '$version' is not installed. Skipping."
  fi
done

if _yavm_item_in_array '--force' "$@"; then
  # _yavm_debug "Clearing golang entries from \$path."
  path=(${path:#$ASDF_DIR/installs/golang/*})
fi

# Remove versions to force pyenv to put it at the top of the path
_yavm_add_entries_to_path_with_prefix "$ASDF_DIR/installs/golang" "${entries_to_add[@]}"
