#!/usr/bin/env zsh

local plugin_name="$1"

if [[ -z "$plugin_name" ]]; then
  echo "Please pass a plugin name"
  return 1
fi

if [[ ! -f "${YAVM_PLUGIN_DIR}/${plugin_name}/list-all" ]]; then
  echo "The ${plugin_name} plugin doesn't support getting the latest version."
  return 1
fi


"${YAVM_PLUGIN_DIR}/${plugin_name}/list-all" | tail -1
