#!/usr/bin/env zsh

# echo "Sourcing:" "$YAVM_PLUGIN_DIR"/"${^@}"/init(.N)
local plugin_init
for plugin_init in "$YAVM_PLUGIN_DIR"/"${^@}"/init(.N); do
  source "$plugin_init"
done
# source "$YAVM_PLUGIN_DIR"/"${^@}"/init(.N)

# echo "${(kv)yavm_version_variables}"
# echo
# echo "${(kv)yavm_version_files}"
# echo
# echo "${(kv)yavm_default_version_files}"


yavm_set_path --force
