#!/usr/bin/env zsh

_yavm_get_versions

local command
for command in ${(k)_yavm_versions}; do
  local enabled_var="YAVM_${command:u}_ENABLED"
  if [[ -n "${(P)enabled_var}" ]]; then
    _yavm_set_path_"${command}" "$@"
  # else
  #   _yavm_debug "Skipping $command."
  fi
done

# _yavm_debug "New \$PATH:"
# local item
# for item in $path; do
#   _yavm_debug " - $item"
# done
