#!/usr/bin/env zsh

local plugin_name="nodejs"

YAVM_PREFIX_NODEJS="${YAVM_INSTALL_DIR}/${plugin_name}/"

yavm_version_variables[${(U)plugin_name}_VERSION]="nodejs"
yavm_version_variables[NODE_VERSION]="nodejs"
yavm_version_files[.node-version]="nodejs"
yavm_version_files[.nvmrc]="nodejs"
yavm_version_files[.tool-versions]="ANY"
