#!/usr/bin/env zsh

local version="$1"
local install_path="$2"
local binary_tar_dir="${YAVM_CACHE_HOME}/nodejs/binaries/${version}"

[[ -d "$install_path" ]] && rm -rf "$install_path"
mkdir -p "$install_path"

[[ -d "$binary_tar_dir" ]] && rm -rf "$binary_tar_dir"
mkdir -p "$binary_tar_dir"
cd "$binary_tar_dir"

local arch="$(uname -s | tr '[:upper:]' '[:lower:]')"
local cpu_type="$(uname -m)"
case "$cpu_type" in
  'x86_64') local cpu_type="x64";;
  'i686') local cpu_type="x86";;
  'aarch64') local cpu_type="arm64";;
esac
local binary_tar_url="https://nodejs.org/dist/v${version}/node-v${version}-${arch}-${cpu_type}.tar.gz"
local binary_tar_file="${binary_tar_dir}/${binary_tar_url:t}"

echo "Downloading ${binary_tar_url} to ${binary_tar_file}"
curl -Lo "$binary_tar_file" -C - "$binary_tar_url" || {
  echo "Failed to download ${binary_tar_url}."
  return 1
}

tar zxf "$binary_tar_file" -C "$install_path" --strip-components=1 || {
  echo "Failed to unarchive ${binary_tar_file}."
  return 1
}

echo "Installed nodejs@v${version} to ${install_path}."
