#!/usr/bin/env zsh

local pattern='go[[:digit:]]+(\.[[:digit:]]+)+\b'

curl 2> /dev/null "https://go.googlesource.com/go/+refs" \
  | grep -E -o '\"/go/\+/refs/tags/go.+?\"' \
  | grep -E -o "$pattern" \
  | tr -d 'go' \
  | sort -k 1,1n -k 2,2n -k 3,3n -t . \
  | uniq
