#!/usr/bin/env zsh

local plugin_name="test"

YAVM_PREFIX_PYTHON="${YAVM_INSTALL_DIR}/${plugin_name}/"

yavm_version_variables[${(U)plugin_name}_VERSION]="${plugin_name}"
yavm_version_files[.${plugin_name}-version]="${plugin_name}"
yavm_version_files[.tool-versions]="ANY"
