#!/usr/bin/env zsh

local version="$1"
local pyenv_path="${YAVM_DATA_DIR}/python/pyenv"
local pyenv_url="https://github.com/pyenv/pyenv.git"
local install_path="$2"

if [[ -z "$versions" ]]; then
  echo "Usage: yavm install python VERSION [VERSION...]"
  return 1
fi

if [[ ! -d "$pyenv_path" ]]; then
  echo "Downloading python-build..."
  git clone "$pyenv_url" "$pyenv_path"
fi

cd "$pyenv_path"

echo "Ensuring python-build is up-to-date..."
git pull || true

"$pyenv_path"/plugins/python-build/bin/python-build \
  "$version" "$install_path"
