#!/usr/bin/env zsh

if [[ -d "$PYENV_ROOT" && ! -d "${PYENV_ROOT}/.git" ]]; then
  cd "$PYENV_ROOT"
  git init || return 1
  git remote add origin https://github.com/pyenv/pyenv.git || return 1
  git fetch --quiet || return 1
  git reset --quiet origin/master || return 1
  git branch --set-upstream-to=origin/master master || return 1
  git checkout --quiet -- "$PYENV_ROOT" || return 1
elif [[ -d "$PYENV_ROOT" ]]; then
  cd "$PYENV_ROOT"
  git branch --set-upstream-to=origin/master master || return 1
  git pull || return 1
else
  git clone https://github.com/pyenv/pyenv.git "$PYENV_ROOT" || return 1
fi

pyenv install "$@"
